### PR TITLE
Add emoji to message format

### LINKED ISSUE #3: Insert emoji option
Would be cool and more intuitive to have an emoji by `level_name` type (⚠️ for warning, etc.). The format would be like this:

`%emoji% %level_name%</b> (%channel%) [%date%]\n\n%message%\n\n%context%%extra%`

If you think this is a good idea, can I be assigned to do it?

### PR DESCRIPTION
**Pull request by paulo-hortelan**
fix #3 

I did as as you asked, just optional

### CODE REVIEW

**Comment by jacklul** [comment]
Instead of function an private array could be used - that would open up a possibility for the user to change the emojis.

`getEmoji` function would be removed.

`$emoji = ` line could become this:
```php
$emoji = $this->emojis[$record['level_name']] ?? $this->emojis['DEFAULT'] ?? '🐞';
```
and the constructor:
```php
        ...
     * @param array  $emojiArray Array containing emojis for each record level name
     */
    public function __construct(bool $html = true, string $format = null, string $dateFormat = null, string $separator = '-', array $emojiArray = null)
    {
        ...
        $emojiArray != null && $this->emojis = $emojiArray;
    }
```

**Comment by paulo-hortelan** [comment]
Ok, but should I define a default array like this?

```php
     ...
    /**
     * @var array
     */
    private $emojis = ["DEBUG" => '🐞', "INFO" => 'ℹ️', "NOTICE" => '📌', "WARNING" => '⚠️', ...]; 

    /**
     * Formatter constructor
     *
     * @param bool   $html       Format as HTML or not
     ...
```

**Comment by jacklul** [comment]
Let's stick with a standards, so:
```php
private $array= [
    'VAR1' => 'VAL',
    'VAR2' => 'VAL',
    'VAR3' => 'VAL',
...
];
```

**Comment by paulo-hortelan** [comment]
Not sure if I did it right, but there you go 😊

**Review by jacklul — APPROVED** [review]

**Comment by jacklul** [comment]
I'll add some tweaks later and then release it, thanks!

**Pull request merged**
